_target_: models.diffusion.ddpm.DDPM
beta_end: 0.05
image_size: 200
logdir: logs/unet_conditional
use_fp16: True
noise_schedule: linear
timesteps: 200
is_conditional: True
criterion: utils.metrics.MetricName
use_ema: True
lr_warmup: 5000
lr_scheduler_config:
  _partial_: true # fully initialized manually
  _target_: torch.optim.lr_scheduler.MultiStepLR
  milestones: [5, 10, 20]
  gamma: 0.1
unet:
  _target_: models.networks.unet_lucas.UNetLucas
  dim: 200
  init_dim: 8
  dim_mults: [1, 2, 4]
  channels: 1
  resnet_block_groups: 8
  learned_sinusoidal_dim: 16

optimizer_config:
  _partial_: true # fully initialized manually
  _target_: torch.optim.Adam
  lr: 1e-4
